# see https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

[versions]
micronaut = "3.4.1"

[libraries]
micronaut_plugin = {module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut" }

[bundles]

[plugins]
